# Generated by Django 3.1.3 on 2020-12-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
